#!/usr/bin/env python3
"""Build supabase/functions/generate-pdf/assets/fonts.generated.ts.

generate-pdf (a Deno Edge Function) embeds the design system's own brand
fonts into invoice PDFs via pdf-lib. Two problems stood between "the font
file exists in vendor/design-system" and "pdf-lib can embed it":

1. assets/fonts/body.woff2 is a *variable* font (Source Sans 3, wght axis
   200-900, default 200 = ExtraLight). pdf-lib/fontkit has no public API to
   pick a specific instance out of a variable font -- embed the file as-is
   and every glyph renders at its default instance, i.e. the whole invoice
   in ExtraLight. Fixed by instantiating two STATIC weights at build time
   with fontTools' varLib.instancer (this script) and committing the result,
   since Deno's edge runtime has no fonttools/harfbuzz to do that at request
   time. The three wordmark faces (wordmark-ecke/-dot/-solutions.woff2) need
   no instancing -- tokens/fonts.css's @font-face rules show each is already
   a single static instance (wght 420/660/580), pre-instantiated the same
   way upstream in the design system.

2. supabase/edge-runtime bundles a function's module graph (eszip) before
   running it and does not carry along sibling non-module files -- a plain
   Deno.readFile("./assets/body-regular.ttf") 404s at request time ("path
   not found: /var/tmp/sb-compile-edge-runtime/..."), confirmed live 6 Sep
   2026 against the self-hosted stack. Fixed by inlining every font's bytes
   as a base64 string constant in a .ts module: base64 text is ordinary
   TypeScript source, so it survives bundling like any other import.

3. pdf-lib's fontkit will happily *parse* a .woff2 file for metrics and
   glyph outlines, but embedding one as-is writes the raw WOFF2-compressed
   container into the PDF's FontFile2 stream, not the decompressed sfnt a
   PDF's font-program stream is actually specified to hold -- Adobe/Chrome's
   renderer tolerates it, but MuPDF/FreeType does not ("FT_New_Memory_Face:
   unknown file format"), confirmed live 6 Sep 2026 rasterizing the output
   with PyMuPDF. Fixed by converting every font -- wordmark faces included,
   not just the two instanced weights -- to a plain sfnt (.ttf) here, so
   nothing woff2-shaped ever reaches pdf-lib.

Run this whenever vendor/design-system's body.woff2 or the three
wordmark-*.woff2 files change:

    pip install fonttools brotli
    python scripts/build-fonts.py

Requires fonttools with brotli support (woff2 decompression) -- `pip install
fonttools brotli`, not just `pip install fonttools`.
"""

import base64
from pathlib import Path

from fontTools import ttLib
from fontTools.varLib.instancer import instantiateVariableFont

REPO_ROOT = Path(__file__).resolve().parent.parent
DS_FONTS = REPO_ROOT / "vendor" / "design-system" / "assets" / "fonts"
PDF_ASSETS = REPO_ROOT / "supabase" / "functions" / "generate-pdf" / "assets"

# (constant name, source file under DS_FONTS or PDF_ASSETS, wght instance or
# None to embed unchanged)
STATIC_INSTANCES = [
    ("body-regular.ttf", DS_FONTS / "body.woff2", 400),
    ("body-bold.ttf", DS_FONTS / "body.woff2", 700),
]
# Already a single static instance each (see the module docstring's point 1)
# -- only the container format needs to change, woff2 -> sfnt.
REPACK_AS_TTF = [
    ("wordmark-ecke.ttf", DS_FONTS / "wordmark-ecke.woff2"),
    ("wordmark-dot.ttf", DS_FONTS / "wordmark-dot.woff2"),
    ("wordmark-solutions.ttf", DS_FONTS / "wordmark-solutions.woff2"),
]
TS_EXPORTS = [
    ("BODY_REGULAR_B64", "body-regular.ttf"),
    ("BODY_BOLD_B64", "body-bold.ttf"),
    ("WORDMARK_ECKE_B64", "wordmark-ecke.ttf"),
    ("WORDMARK_DOT_B64", "wordmark-dot.ttf"),
    ("WORDMARK_SOLUTIONS_B64", "wordmark-solutions.ttf"),
]


def build_static_instances() -> None:
    for out_name, src, wght in STATIC_INSTANCES:
        tt = ttLib.TTFont(str(src))
        instantiateVariableFont(tt, {"wght": wght}, inplace=True)
        tt.flavor = None  # plain sfnt (.ttf), not woff2 -- pdf-lib/fontkit reads either fine
        out_path = PDF_ASSETS / out_name
        tt.save(str(out_path))
        print(f"instantiated {src.name} @ wght={wght} -> {out_path.relative_to(REPO_ROOT)}")


def repack_as_ttf() -> None:
    """woff2 -> sfnt for fonts that are already the right weight/style --
    no instancer step, just strip the WOFF2 container (see docstring point 3)."""
    for out_name, src in REPACK_AS_TTF:
        tt = ttLib.TTFont(str(src))
        tt.flavor = None
        out_path = PDF_ASSETS / out_name
        tt.save(str(out_path))
        print(f"repacked {src.relative_to(REPO_ROOT)} (woff2) -> {out_path.relative_to(REPO_ROOT)} (sfnt)")


def write_generated_ts() -> None:
    lines = [
        "// GENERATED by scripts/build-fonts.py -- do not hand-edit.",
        "//",
        "// Supabase's edge-runtime bundles a function's module graph (eszip) before",
        '// running it and does NOT carry along sibling non-module files -- a plain',
        '// Deno.readFile("./assets/body-regular.ttf") 404s at request time',
        '// ("path not found: /var/tmp/sb-compile-edge-runtime/..."), verified live',
        "// 6 Sep 2026 against the self-hosted stack. Inlining the font bytes as base64",
        "// string constants makes them part of the module graph like any other",
        "// TypeScript source, so they survive bundling.",
        "//",
        "// Regenerate after changing any source font: see scripts/build-fonts.py's",
        "// module docstring.",
        "",
    ]
    for const_name, fname in TS_EXPORTS:
        b64 = base64.b64encode((PDF_ASSETS / fname).read_bytes()).decode("ascii")
        chunk_size = 120
        chunks = [b64[i : i + chunk_size] for i in range(0, len(b64), chunk_size)]
        lines.append(f"export const {const_name} =")
        lines.append("  " + " +\n  ".join(f'"{c}"' for c in chunks) + ";")
        lines.append("")

    out_path = PDF_ASSETS / "fonts.generated.ts"
    out_path.write_text("\n".join(lines) + "\n", newline="\n")
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    PDF_ASSETS.mkdir(parents=True, exist_ok=True)
    build_static_instances()
    repack_as_ttf()
    write_generated_ts()
